# Name this workflow
name: Build C++ for Linux (x86_64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository's code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Install 64-bit build dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake build-essential libssl-dev zlib1g-dev

      # 3. Download header-only dependencies
      - name: Download Header Dependencies
        run: |
          # --- FIX ---
          # Add --fail to make curl exit with an error if the download fails (e.g., 404)
          curl --fail -L "https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h" -o httplib.h
          curl --fail -L "https://github.com/nlohmann/json/releases/latest/download/json.hpp" -o json.hpp
          curl --fail -L "https://raw.githubusercontent.com/vincentlaucsien/csv-parser/master/single_include/csv.h" -o csv.h
          
      # 4. Configure CMake
      - name: Configure CMake
        run: cmake -S . -B build

      # 5. Build with CMake
      - name: Build with CMake
        run: cmake --build build

      # 6. Upload the 64-bit binary as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-binary
          path: build/bin/mission_converter
